version: "3.7"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: dpage/pgadmin4:8
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050         # <— make pgAdmin listen on 5050
      # Optional: make initial connection to the "db" service appear in Servers
      - PGADMIN_CONFIG_SERVER_MODE=True
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      # Optional: auto-register a server (see servers.json below)
      - ./servers.json:/pgadmin4/servers.json:ro
    # Do NOT publish ports; Umbrel's Traefik handles ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trilogic-postgres-pgadmin.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.services.trilogic-postgres-pgadmin.loadbalancer.server.port=5050"  # <— matches PGADMIN_LISTEN_PORT
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5050/misc/ping || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60

volumes:
  db-data:
  pgadmin-data:
