version: "3.8"

services:
  # Umbrel’s proxy forwards the App tile → this target
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 5050
      APP_PROTOCOL: http

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_PASSWORD}     # Umbrel-generated per-app password
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${APP_DATA_DIR}/db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${APP_PASSWORD}   # matches App Password in Umbrel UI
      PGADMIN_LISTEN_PORT: "5050"
      SERVER_MODE: "True"
    volumes:
      - ${APP_DATA_DIR}/pgadmin-data:/var/lib/pgadmin
    expose:
      - "5050"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1/misc/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  # OPTIONAL: uncomment ONLY if you also want direct host access on :5050
  # (Umbrel generally prefers not binding host ports.)
  # web_host:
  #   image: dpage/pgadmin4:8
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${APP_PASSWORD}
  #     PGADMIN_LISTEN_PORT: "5050"
  #     SERVER_MODE: "True"
  #   volumes:
  #     - ${APP_DATA_DIR}/pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - "5050:5050"
