manifestVersion: 1
id: trilogic-postgres-pgadmin
name: PostgreSQL + pgAdmin
category: Development
tagline: Run PostgreSQL and pgAdmin on Umbrel.
version: "0.1.6"  # bump so Umbrel redeploys
description: "PostgreSQL database server with pgAdmin web UI. On first install, this app wipes pgAdmin's data directory and creates the default admin account shown below. Uninstalling does NOT remove your pgAdmin settings or password. To reset credentials, delete the pgadmin-data volume before reinstalling."
developer: "Andrew Friedl"
repo: https://github.com/TriLogic/umbrel
support: https://github.com/TriLogic/umbrel/issues
port: 5050
icon: icon.svg

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgadmin
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_LISTEN_PORT: "5050"
      SERVER_MODE: "True"
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    command: >
      sh -c '
      FLAG_FILE=/var/lib/pgadmin/.initialized;
      if [ ! -f "$FLAG_FILE" ]; then
        echo "First run — wiping pgAdmin data directory...";
        rm -rf /var/lib/pgadmin/*;

        echo "Initializing pgAdmin database...";
        python3 /pgadmin4/setup_db.py --load-servers /dev/null >/dev/null 2>&1 || true;

        echo "Creating default admin user...";
        python3 - <<PY
from pgadmin4 import app
from pgadmin.model import db, User
with app.app_context():
    if not User.query.filter_by(email="admin@example.com").first():
        u = User(email="admin@example.com")
        u.set_password("change-me")
        u.active = True
        u.confirmed = True
        db.session.add(u)
        db.session.commit()
        print("Default admin user created.")
    else:
        print("Admin user already exists.")
PY

        touch "$FLAG_FILE";
      else
        echo "pgAdmin already initialized — skipping reset.";
      fi;
      exec /entrypoint.sh
      '

volumes:
  db-data:
  pgadmin-data:
