manifestVersion: 1
id: trilogic-postgres-pgadmin
name: PostgreSQL + pgAdmin
category: Development
tagline: Run PostgreSQL and pgAdmin on Umbrel.
version: "0.1.2"  # bump version so Umbrel redeploys
description: "PostgreSQL database server with pgAdmin web UI"
developer: "Andrew Friedl"
repo: https://github.com/TriLogic/umbrel
support: https://github.com/TriLogic/umbrel/issues
port: 5050
icon: icon.svg

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgadmin
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: change-me
      PGADMIN_LISTEN_PORT: "5050"
      SERVER_MODE: "True"
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    # This entrypoint script clears pgAdmin's data if it's a fresh install
    entrypoint: >
      sh -c '
      if [ ! -f /var/lib/pgadmin/pgadmin4.db ]; then
        echo "Initializing pgAdmin with default credentials..."
        rm -rf /var/lib/pgadmin/*
      fi
      exec /entrypoint.sh
      '

volumes:
  db-data:
  pgadmin-data:
