manifestVersion: 1
id: trilogic-postgres-pgadmin
name: PostgreSQL + pgAdmin
category: Development
tagline: Run PostgreSQL and pgAdmin on Umbrel.
version: "0.1.7"  # bump so Umbrel redeploys
description: "PostgreSQL database server with pgAdmin web UI. On first install, this app sets the pgAdmin admin account password from the configuration below. This setup runs only once and does not affect existing data or future restarts. Uninstalling does NOT remove your pgAdmin settings or password. To reset credentials, delete the pgadmin-data volume before reinstalling."
developer: "Andrew Friedl"
repo: https://github.com/TriLogic/umbrel
support: https://github.com/TriLogic/umbrel/issues
port: 5050
icon: icon.svg

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgadmin
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: change-me
      PGADMIN_LISTEN_PORT: "5050"
      SERVER_MODE: "True"
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    command: >
      sh -c '
      FLAG_FILE=/var/lib/pgadmin/.password_set;
      if [ ! -f "$FLAG_FILE" ]; then
        echo "Setting pgAdmin admin password from config for first time...";
        python3 - <<PY
from pgadmin4 import app
from pgadmin.model import db, User
import os
email = os.environ.get("PGADMIN_DEFAULT_EMAIL", "admin@example.com")
pw = os.environ.get("PGADMIN_DEFAULT_PASSWORD", "change-me")
with app.app_context():
    u = User.query.filter_by(email=email).first()
    if u:
        u.set_password(pw)
        db.session.commit()
        print(f"Updated password for {email}")
    else:
        u = User(email=email)
        u.set_password(pw)
        u.active = True
        u.confirmed = True
        db.session.add(u)
        db.session.commit()
        print(f"Created new admin user {email}")
PY
        touch "$FLAG_FILE";
      else
        echo "Password already set — skipping.";
      fi;
      exec /entrypoint.sh
      '

volumes:
  db-data:
  pgadmin-data:
