manifestVersion: 1
id: trilogic-postgres-pgadmin
name: PostgreSQL + pgAdmin
category: Development
tagline: Run PostgreSQL and pgAdmin on Umbrel.
version: "0.1.3"  # bump so Umbrel redeploys
description: "PostgreSQL database server with pgAdmin web UI"
developer: "Andrew Friedl"
repo: https://github.com/TriLogic/umbrel
support: https://github.com/TriLogic/umbrel/issues
port: 5050
icon: icon.svg

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgadmin
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: change-me
      PGADMIN_LISTEN_PORT: "5050"
      SERVER_MODE: "True"
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    entrypoint: >
      sh -c '
      FLAG_FILE=/var/lib/pgadmin/.initialized;
      if [ ! -f "$FLAG_FILE" ]; then
        echo "First run detected — resetting pgAdmin data directory...";
        rm -rf /var/lib/pgadmin/*;
        echo "FORCED_USER = \"$PGADMIN_DEFAULT_EMAIL\"" >> /pgadmin4/config_local.py;
        echo "FORCED_PASSWORD = \"$PGADMIN_DEFAULT_PASSWORD\"" >> /pgadmin4/config_local.py;
        touch "$FLAG_FILE";
      else
        echo "pgAdmin already initialized — skipping reset.";
      fi;
      exec /entrypoint.sh
      '

volumes:
  db-data:
  pgadmin-data:
