version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: hello-umbrel_web_1
      APP_PORT: 80
      APP_PROTOCOL: http
      PROXY_AUTH_ADD: "false"

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/html:/usr/share/nginx/html:ro
    expose:
      - "80"

